<h1 align="center">Dynamic Programming</h1>

- When developing a **dynamic-programming algorithm**, we follow a sequence of **four steps**:
  1. **Characterize** the structure of an optimal solution.
  2. **Define** recursively  the value of an optimal solution.
  3. **Compute** the value of an optimal solution (typically in a bottom-up fashion).
  4. **Construct** an optimal solution from computed information.

<h1 align="center">Longest Common Subsequence</h1>



  
   
- **Longest-Common-Subsequence problem**:

  Given **two sequences** $X = \left \langle x_1, x_2, ..., x_m \right \rangle$ and $Y = \left \langle y_1, y_2, ..., y_n \right \rangle$, find a **maximum length common subsequence** of $X$ and $Y$ .
  
  
- A sequence $Z$ is a **common subsequence** of $X$ and $Y$ if $Z$ is a **subsequence** of both $X$ and  $Y$.


- We say that a sequence $Z = \left \langle z_1, z_2, ..., z_k \right \rangle$ is a **subsequence** of $X$ if there exists a strictly increasing sequence $\left \langle i_1, i_2, ..., i_k \right \rangle$ of indices of $X$ such that for all $j = 1, 2, ... , k$, we have $x_{i_j} = z_j$.

- Let us define $c[i, j]$ to be the **length of an LCS** of the sequences $X_i$ and $Y_j$.

  The optimal substructure of the LCS problem gives the recursive formula:
  
  $$c[i, j] = 
  \left\{\begin{matrix}
  0, & \text{ if } i=0 \text{ or } j=0, \\
  c[i-1,j-1] + 1, & \text{ if } i,j>0 \text{ and } x_i = y_j, \\
  \max \left ( c[i, j-1], c[i-1, j] \right ), & \text{ if } i,j >0 \text{ and } x_i \neq y_j. 
  \end{matrix}\right.  
  $$
  

- Using the recurence equation, we **can use dynamic programming** to compute the solutions **bottom up**:

  Procedure `lengthLCS(X,Y)` takes two sequences $X = \left \langle x_1, x_2, ..., x_m \right \rangle$ and $Y = \left \langle y_1, y_2, ..., y_n \right \rangle$ as inputs. 

  It stores the $c[i,j]$ values in a table $c[0..m, 0..n]$, and it computes the entries in **row-major** order.
  
  The procedure also maintains the table $b[1..m, 1..n]$ to help us **construct an optimal solution**.

In [143]:
import numpy as np

def lengthLCS(X,Y):
    m = len(X)
    n = len(Y)
    b = np.zeros((m+1,n+1), dtype = str)
    c = np.zeros((m+1,n+1))
    for i in range (0, m):
        for j in range(0,n):
            if X[i] == Y[j]:
                c[i+1,j+1] = c[i,j] + 1
                b[i+1,j+1] = 'D' # left up diagonal arrow
            elif c[i,j+1] >= c[i+1,j]:
                c[i+1,j+1] = c[i,j+1]
                b[i+1,j+1] = 'U' # up arrow
            else:
                c[i+1,j+1] = c[i+1, j]
                b[i+1,j+1] = 'L' # left arrow
    return b, c                

In [144]:
X = ['A', 'B', 'C', 'B', 'D', 'A', 'B']
Y = ['B', 'D', 'C', 'A', 'B', 'A']

b,c  = lengthLCS(X,Y)
print("b = \n", b, "\n \n c = \n", c)

b = 
 [['' '' '' '' '' '' '']
 ['' 'U' 'U' 'U' 'D' 'L' 'D']
 ['' 'D' 'L' 'L' 'U' 'D' 'L']
 ['' 'U' 'U' 'D' 'L' 'U' 'U']
 ['' 'D' 'U' 'U' 'U' 'D' 'L']
 ['' 'U' 'D' 'U' 'U' 'U' 'U']
 ['' 'U' 'U' 'U' 'D' 'U' 'D']
 ['' 'D' 'U' 'U' 'U' 'D' 'U']] 
 
 c = 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 2. 2.]
 [0. 1. 1. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 3. 3.]
 [0. 1. 2. 2. 2. 3. 3.]
 [0. 1. 2. 2. 3. 3. 4.]
 [0. 1. 2. 2. 3. 4. 4.]]


- Figure below shows the tables produced by `lengthLCS(X,Y)` procedure on the sequences $X = \left \langle A, B, C, B, D, A, B\right \rangle$ and $Y = \left \langle B, D, C, A, B, A \right \rangle$. 

  The **running time** of the procedure is $\Theta(mn)$, since each **table entry takes** $\Theta(1)$ **time to compute**.
  
  
<center><img src="images/S7_Table.png" width="500" alt="Example" /></center>


- The following recursive procedure **prints out** an LCS of $X$ and $Y$ in the proper, forward order.

In [145]:
def printLCS(b, X, i, j):
    if i == 0 or j == 0:
        return
    if b[i,j] == 'D':
        printLCS(b, X, i-1, j-1)
        print(X[i-1])
    elif b[i,j] == "U":
        printLCS(b, X, i-1, j)
    else:
        printLCS(b, X, i, j-1)
        
printLCS(b, X, len(X), len(Y))

B
C
B
A


<h1 align="center">Exercise 1</h1>

- Determine an **LCS** of $X = \left \langle 1, 0, 0, 1, 0, 1, 0, 1 \right \rangle$ and $Y = \left \langle 0, 1, 0, 1, 1, 0, 1, 1, 0 \right \rangle$.

  1. Find a solution manually.
  2. Write the code and get an answer.

In [146]:
X = [1, 0, 0, 1, 0, 1, 0, 1]
Y = [0, 1, 0, 1, 1, 0, 1, 1, 0]

b,c  = lengthLCS(X,Y)
print("b = \n", b)
print("c = \n", c)
printLCS(b, X, len(X), len(Y))

b = 
 [['' '' '' '' '' '' '' '' '' '']
 ['' 'U' 'D' 'L' 'D' 'D' 'L' 'D' 'D' 'L']
 ['' 'D' 'U' 'D' 'L' 'L' 'D' 'L' 'L' 'D']
 ['' 'D' 'U' 'D' 'U' 'U' 'D' 'L' 'L' 'D']
 ['' 'U' 'D' 'U' 'D' 'D' 'U' 'D' 'D' 'L']
 ['' 'D' 'U' 'D' 'U' 'U' 'D' 'U' 'U' 'D']
 ['' 'U' 'D' 'U' 'D' 'D' 'U' 'D' 'D' 'U']
 ['' 'D' 'U' 'D' 'U' 'U' 'D' 'U' 'U' 'D']
 ['' 'U' 'D' 'U' 'D' 'D' 'U' 'D' 'D' 'U']]
c = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 2. 3. 3. 3. 3.]
 [0. 1. 2. 2. 3. 3. 3. 4. 4. 4.]
 [0. 1. 2. 3. 3. 3. 4. 4. 4. 5.]
 [0. 1. 2. 3. 4. 4. 4. 5. 5. 5.]
 [0. 1. 2. 3. 4. 4. 5. 5. 5. 6.]
 [0. 1. 2. 3. 4. 5. 5. 6. 6. 6.]]
1
0
0
1
1
0


<h1 align="center">Exercise 2</h1>

- Write a code that **reconstruct an LCS** from the completed $c$ **table** and the **original sequences** $X$ and $Y$ in $O(m+n)$ time **without** using the $b$ **table**.

In [148]:
def printLCS2(c, X, i, j):
    if i == 0 or j == 0:
        return
    if (c[i,j] == c[i-1,j] + 1) and (c[i,j] == c[i,j-1] + 1):
        printLCS2(c, X, i-1, j-1)
        print(X[i-1])
    elif c[i,j] == c[i-1,j]:
        printLCS2(c, X, i-1, j)
    else:
        printLCS2(c, X, i, j-1)

X = [1, 0, 0, 1, 0, 1, 0, 1]
Y = [0, 1, 0, 1, 1, 0, 1, 1, 0]        
        
printLCS2(c, X, len(X), len(Y))          

1
0
1
0
1
0


In [6]:
X

[1, 0, 0, 1, 0, 1, 0, 1]

<h1 align="center">Exercise 3</h1>

- Show how to compute the **length of an LCS** using only $2 \cdot min(m,n)$ entries in the $c$ table plus $O(1)$ additional space. 

- Since we need only two rows of $c$ table at a time, we can reduce the asymptotic space requirements for lenght of an LCS.

In [64]:
import numpy as np

def lengthLCS2(X,Y):
    if len(X) < len(Y):
        X, Y = Y, X
    m = len(X)
    n = len(Y)
    c = np.zeros((2, n+1))
    k = 0
    l = 1
    for i in range (0, m):
        print(c[k])
        for j in range(0,n):
            if X[i] == Y[j]:
                c[l,j+1] = c[k,j] + 1
            elif c[l,j] <= c[k,j+1]:
                c[l,j+1] = c[k,j+1]
            else:
                c[l,j+1] = c[l, j]
        k , l = l , k
    print(c[k])
    return c   

X = ['A', 'B', 'C', 'B', 'D', 'A', 'B']
Y = ['B', 'D', 'C', 'A', 'B', 'A']

c  = lengthLCS2(X,Y)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 1. 1.]
[0. 1. 1. 1. 1. 2. 2.]
[0. 1. 1. 2. 2. 2. 2.]
[0. 1. 1. 2. 2. 3. 3.]
[0. 1. 2. 2. 2. 3. 3.]
[0. 1. 2. 2. 3. 3. 4.]
[0. 1. 2. 2. 3. 4. 4.]


<h1 align="center">Exercise 4</h1>

- Now show how to do **the same thing**, but using $min(m,n)$ entries plus $O(1)$ additional space.

In [80]:
import numpy as np

def lengthLCS3(X,Y):
    if len(X) < len(Y):
        X, Y = Y, X
    m = len(X)
    n = len(Y)
    c = np.zeros(n+1)
    D, U, L  = 0, 0, 0
    for i in range (0, m):
        print(c)
        D, U, L = 0, 0, 0
        for j in range(0,n):
            U = c[j+1]
            if X[i] == Y[j]:
                c[j+1] = D + 1
                L = c[j+1]
            elif L >= U:
                c[j+1] = L
            else:
                c[j+1] = U
            D = U
    print(c)
    return c   

X = ['A', 'B', 'C', 'B', 'D', 'A', 'B']
Y = ['B', 'D', 'C', 'A', 'B', 'A']

c  = lengthLCS3(X,Y)

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 1. 1.]
[0. 1. 1. 1. 1. 2. 2.]
[0. 1. 1. 2. 2. 2. 2.]
[0. 1. 1. 2. 2. 3. 3.]
[0. 1. 2. 2. 2. 3. 3.]
[0. 1. 2. 2. 3. 3. 4.]
[0. 1. 2. 2. 3. 4. 4.]


<h1 align="center">Exercise 5</h1>

- Given a sequence $X$ of $n$ numbers.


- Write an algorithm that finds the **longest monotonically increasing subsequence** of $X$ in $O(n^2)$ time.

In [124]:
import numpy as np

def longestMIS(X):
    n = len(X)
    c = np.ones(n)
    a = 0
    m = 1
    for i in range(0, n-1):
        j = i+1
        while X[j-1] <= X[j] and j < n-1:
            c[i] = c[i] + 1
            j = j + 1
        if j - i > m:
            m = j - i
            a = i
    return c, a, m

X = [5, 6, 1, 2, 3, 4, 9, 8, 7]

c, a, m = longestMIS(X)
print(c)
print(a, m)
b = a+m
print(X[a:b])

[2. 1. 5. 4. 3. 2. 1. 1. 1.]
2 5
[1, 2, 3, 4, 9]


<h1 align="center">Exercise 6</h1>

- Given a sequence $X$ of $n$ numbers.


- **Usind Dynamic Programming**, write an algorithm that finds the **longest monotonically increasing subsequence** of $X$ in $O(n)$ time.

In [149]:
import numpy as np

def longestMIS2(X, c, n):
    if n == 0:
        return
    if X[n] >= X[n-1]:
        longestMIS(X, c, n-1)
        c[n] = c[n-1] + 1
    else:
        longestMIS(X, c, n-1)

X = [5, 6, 1, 2, 3, 4, 9, 8, 7]

c = np.ones(len(X))
longestMIS2(X, c, len(X)-1)
print(c)

b = np.argmax(c)
m = int(np.max(c))
print(b,m)
a = b-m
print(X[a+1:b+1])

[1. 2. 1. 2. 3. 4. 5. 1. 1.]
6 5
[1, 2, 3, 4, 9]


<h1 align="center">End of Seminar</h1>