<h1 align="center">Dynamic Programming</h1>

- **Dynamic programming**, like the divide-and-conquer method, **solves problems recursively by combining the solutions to subproblems**.


- The **main difference** is that dynamic programming applies when the **subproblems overlap**, i.e. when **subproblems share subsubproblems**.


- The **dynamic programming** is applied to **optimization problems**.

  In other words, a problem have **many possible solutions** and we wish to **find a solution** with the **optimal (minimum or maximum) value**.
  

- Since there may be several solutions that achieve the optimal value, we call such a solution **an optimal solution**, as opposed to **the optimal solution**.


- When developing a **dynamic-programming algorithm**, we follow a sequence of **four steps**:
  1. **Characterize** the structure of an optimal solution.
  2. **Define** recursively  the value of an optimal solution.
  3. **Compute** the value of an optimal solution (typically in a bottom-up fashion).
  4. **Construct** an optimal solution from computed information.
  

- **Note**: If we **need only the value** of an optimal solution, and not the solution itself, then we **can omit step 4**.

<h2 align="center">Rod Cutting Problem</h2>

- Our **first example** uses dynamic programming to solve a simple problem in **deciding where to cut steel rods**.



- **Problem Statement**: 

  Given a **rod** of **length $n$ inches** and a **table of prices** $p_i$ for $i = 1, 2, ..., n$.
  
  **Our task** is to determine the **maximum revenue** $r_n$ obtainable by **cutting up** the rod and **selling the pieces**. 
  
  The **rod length** should always be an **integral number of inches**.
  

- In general, we can **cut up** a rod of **length** $n$ in $2^{n-1}$ **different ways**!


- We **denote** a **decomposition into pieces** using **ordinary additive notation**, so that:

  $$7 = 2 + 2 + 3,$$
 
  indicates that a **rod of length** $7$ is **cut** into **three pieces** — **two** of **length** $2$ and **one** of **length** $3$.
  

- If an **optimal solution** cuts the rod into $k$ **pieces**, for some $1 \leq k \leq n$, then an optimal decomposition can be written as:

  $$n = i_1 + i_2 + \cdots + i_k$$
  
  of the rod into pieces of lengths $i_1, i_2, . . . , i_k$ provides **maximum** corresponding **revenue**:
  
  $$r_n = p_{i_1} + p_{i_2} + \cdots + p_{i_k}.$$

<h3 align="center">Example</h3>

- As an **example**, let's consider a sample **price table** for rods:

| Length $i$  | 1 | 2 | 3 | 4 |  5 |  6 |  7 |  8 |  9 | 10 |
|-------------|:-:|:-:|:-:|:-:|:--:|:--:|:--:|:--:|:--:|:--:|
| price $p_i$ | 1 | 5 | 8 | 9 | 10 | 17 | 17 | 20 | 24 | 30 |

- The **8 possible** ways of **cutting up** a rod of **length** $4$ is shown below. 

  <center><img src="images/L6_Rod.png" width="1000" alt="Example" /></center>

  **Above each piece** is the **value** of that piece, according to the sample price table.
  
  The **optimal strategy** is **cutting the rod** into **two pieces** of **length 2** — which has **total value 10**.
  

- We can **determine** the **optimal revenue** $r_i$, for $i =  1, 2, ..., 10$ by inspection, with the corresponding optimal decompositions:

|          |   |    |               |    |   |     |
|:---------|:-:|:---|:-------------:|:---|:-:|:----|
| $r_1$    | = |  1 | from solution | 1  | = | 1   |
| $r_2$    | = |  5 | from solution | 2  | = | 2   |
| $r_3$    | = |  8 | from solution | 3  | = | 3   |
| $r_4$    | = | 10 | from solution | 4  | = | 2+2 |
| $r_5$    | = | 13 | from solution | 5  | = | 2+3 |
| $r_6$    | = | 17 | from solution | 6  | = | 6   |
| $r_7$    | = | 18 | from solution | 7  | = | 1+6 or 2+2+3 |
| $r_8$    | = | 22 | from solution | 8  | = | 2+6 |
| $r_9$    | = | 25 | from solution | 9  | = | 3+6 |
| $r_{10}$ | = | 30 | from solution | 10 | = | 10  |



- **More generally**, we can frame the values $r_n$ for $n \geq 1$ in terms of **optimal revenues** from shorter rods:

  $$r_n = \max (p_n, r_1 + r_{n-1}, r_2 + r_{n-2}, ..., r_{n-1} + r_1),$$
  
  where the **first argument**, $p_n$, corresponds to making **no cuts** at all and selling the rod of length $n$ as is.


- In a related, but slightly **simpler**, way to arrange a **recursive structure** for the rodcutting problem is as follows:

  View a **decomposition** as **consisting** of a **first piece of length $i$** cut off the **left-hand** end, and then a **right-hand** remainder of **length** $n-i$. 

  **Only the remainder**, and not the first piece, may be **further divided**.
  

- When doing so, we can **couch the solution** with **no cuts** at all as **saying** that the **first piece** has **size** $ =n $ and **revenue** $p_n$ and that the **remainder** has **size** $0$ with corresponding **revenue** $r_0 = 0$. 

  We thus obtain the following simpler version of equation:
  
  $$r_n = \max_{i \leq < n} (p_i + r_{n-i}).$$
  
  In this formulation, an **optimal solution** embodies the solution to **only one** related **subproblem** rather than two.

<h3 align="center">Recursive Top-Down Implementation</h3>

- The following procedure implements top-down recursive computation:

In [1]:
import numpy as np

def cutRod(p, n):
    if n == 0:
        return 0
    q = -np.infty
    for i in range(1, n+1):
        q = max(q, p[i-1] + cutRod(p, n-i))
    return q

p = [1, 5, 8, 9, 10, 17, 17, 20, 24, 30]

for i in range(1,len(p)+1):
    print(cutRod(p, i))


1
5
8
10
13
17
18
22
25
30


In [2]:
q = [2**k for k in range(1,25)]
for i in range(1,len(q)+1):
    %time cutRod(q, i)

Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 0 ns
Wall time: 999 µs
Wall time: 1 ms
Wall time: 2 ms
Wall time: 4 ms
Wall time: 7 ms
Wall time: 18 ms
Wall time: 32 ms
Wall time: 63 ms
Wall time: 136 ms
Wall time: 284 ms
Wall time: 471 ms
Wall time: 937 ms
Wall time: 1.76 s
Wall time: 3.71 s
Wall time: 7.07 s
Wall time: 15 s


- **Why** is `cutRoad` procedure so **inefficient**?

  The problem is that `cutRoad` procedure **calls itself recursively over and over again** with the **same parameter values**.
  
  In other words, **it solves** the **same subproblems repeatedly**.
  
- The **recursion tree** showing recursive calls resulting from a call `cutRoad` procedure for $n = 4$ is shown below:
  
  <center><img src="images/L6_cutRod.png" width="600" alt="Example" /></center>
  
- In general, this recursion tree has $2^n$ and $2^{n-1}$ leaves, so the running time of `cutRoad` procedurecan be written as:

  $$T(n) = 1 + \sum_{i=1}^{n-1} T(i).$$
  
  Solving this recurrence with substitution we can obtain:
  
  $$T(n) = 2^n.$$


<h3 align="center">Using Dynamic Programming for Optimal Rod Cutting</h3>

There are **two ways** to to **convert** `cutRoad` procedure **into** an **efficient algorithm**, using **dynamic programming**:


1. The **first** approach is **top-down with memoization**.
  
   In this approach, we write the procedure recursively in a natural manner, but modified to **memorize the result of each subproblem**.
  

2. The **second** approach is the **bottom-up method**.

  This approach typically depends on some natural notion of the **size** of a subproblem.
  
  Thus, **solving any particular subproblem** depends only on **solving smaller subproblems**.

  We **sort** the subproblems **by size** and **solve** them **in size order**, smallest first.

In [3]:
#  1. Top-down with memoization

import numpy as np

def memorizedCutRod(p, n):
    r = [-np.infty] * n
    return memorizedCutRodAux(p, n, r)

def memorizedCutRodAux(p, n, r):
    if r[n-1] >= 0:
        return r[n-1]
    if n == 0:
        q = 0
    else:
        q = -np.infty
        for i in range(1, n+1):
            q = max(q, p[i-1] + memorizedCutRodAux(p, n-i, r))
    r[n-1] = q
    return q

p = [1, 5, 8, 9, 10, 17, 17, 20, 24, 30]

for i in range(1,len(p)+1):
    print(memorizedCutRod(p, i))

1
5
8
10
13
17
18
22
25
30


In [5]:
#  2. Bottom-up method

import numpy as np

def bottomUpCutRod(p, n):
    r = [-np.infty] * (n+1)
    r[0] = 0
    for j in range(1, n+1):
        q = -np.infty
        for i in range(1, j+1):
            q = max(q, p[i-1] + r[j-i])
        r[j] = q
    return r[n]

p = [1, 5, 8, 9, 10, 17, 17, 20, 24, 30]

for i in range(1,len(p)+1):
    print(bottomUpCutRod(p, i))        

1
5
8
10
13
17
18
22
25
30


- It's easy to check that the **bottom-up** and **top-down** versions have the same asymptotic running time equal to $T(n) = \Theta(n^2)$

<h3 align="center">Subproblem Graphs</h3>

- The **subproblem graph** for the rod-cutting problem example with $n = 4$ is shown below:


  <center><img src="images/L6_Subproblem_Graph.png" width="200" alt="Example" /></center>

- As we can see, it is a directed graph, containing **one vertex** for **each distinct subproblem**.


- We can think of the subproblem graph as a **reduced** or **collapsed** version of the recursion tree for the **top-down recursive method**, in which we **coalesce** **all nodes** for the same subproblem **into a single vertex** and **direct all edges** from parent to **child**.

<h3 align="center">Reconstructing a Solution</h3>

- What do we miss? Thats right, solution!


- Here is an **extended** version of `bottomUpCutRod` procedure that **also computes**, for each rod size $j$ the **optimal size** of the **first piece to cut off** $s_j$:

In [6]:
import numpy as np

def extendedBottomUpCutRod(p, n):
    r = [-np.infty] * (n+1)
    s = [0] * (n+1)
    r[0] = 0
    for j in range(1, n+1):
        q = -np.infty
        for i in range(1, j+1):
            if q < p[i-1] + r[j-i]:
                q = max(q, p[i-1] + r[j-i])
                s[j] = i
        r[j] = q
    return r, s

p = [1, 5, 8, 9, 10, 17, 17, 20, 24, 30]

for i in range(1,len(p)+1):
    print(extendedBottomUpCutRod(p, i))       

([0, 1], [0, 1])
([0, 1, 5], [0, 1, 2])
([0, 1, 5, 8], [0, 1, 2, 3])
([0, 1, 5, 8, 10], [0, 1, 2, 3, 2])
([0, 1, 5, 8, 10, 13], [0, 1, 2, 3, 2, 2])
([0, 1, 5, 8, 10, 13, 17], [0, 1, 2, 3, 2, 2, 6])
([0, 1, 5, 8, 10, 13, 17, 18], [0, 1, 2, 3, 2, 2, 6, 1])
([0, 1, 5, 8, 10, 13, 17, 18, 22], [0, 1, 2, 3, 2, 2, 6, 1, 2])
([0, 1, 5, 8, 10, 13, 17, 18, 22, 25], [0, 1, 2, 3, 2, 2, 6, 1, 2, 3])
([0, 1, 5, 8, 10, 13, 17, 18, 22, 25, 30], [0, 1, 2, 3, 2, 2, 6, 1, 2, 3, 10])


- As we can see, the call `extendedBottomUpCutRod` procedure returns the following arrays:

| $i$    | 0 | 1 | 2 | 3 |  4 |  5 |  6 |  7 |  8 |  9 | 10 |
|:------:|:-:|:-:|:-:|:-:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| $r[i]$ | 0 | 1 | 5 | 8 | 10 | 13 | 17 | 18 | 22 | 25 | 30 |
| $s[i]$ | 0 | 1 | 2 | 3 |  2 |  2 |  6 |  1 |  2 |  3 | 10 |

<h2 align="center">Matrix-Chain Multiplication</h2>

- Our **next example** of **dynamic programming** is an algorithm that solves the problem of **matrix-chain multiplication**.


- **Problem Statement**: We are given a **sequence** (**chain**) $\left \langle A_1, A_2, ..., A_n  \right \rangle $ of $n$ **matrices** to be multiplied, and **we wish to compute the product**:

  $$A_1  A_2   A_3   \cdots  A_n.$$

 
 
- For example, if the chain of matrices is $\left \langle A_1, A_2, A_3, A_4\right \rangle $, then we can **fully parenthesize** the product $A_1  A_2   A_3   A_4.$ in **five distinct ways**:

  $$(A_1  (A_2  (A_3  A_4))).$$
  $$(A_1  ((A_2  A_3)  A_4)).$$
  $$((A_1  A_2)  (A_3  A_4)).$$
  $$((A_1  (A_2  A_3))  A_4).$$
  $$(((A_1  A_2) A_3)  A_4).$$


- The **standard algorithm** is given by the following procedure, which generalizes the `sqaureMatrixMultiplication` procedure:

In [7]:
import numpy as np

def matrixMultiply(A,B):
    nrowsA, ncolsA = A.shape
    nrowsB, ncolsB = B.shape
    if ncolsA != nrowsB:
        print("Incompatible dimensions!")
        return -1
    else:
        C = np.empty((nrowsA,ncolsB))
        count = 0
        for i in range(nrowsA):
            for j in range(ncolsB):
                C[[i],[j]] = 0
                for k in range(ncolsA):
                    C[[i],[j]] = C[[i],[j]] + A[[i],[k]] * B[[k],[j]]
                    count = count + 1
        print(count)
        return C

A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
C = matrixMultiply(A,B)
C

8


array([[ 7., 10.],
       [15., 22.]])

- If $A$ is a $p \times q$ matrix and $B$ is a $q \times r$ matrix, the resulting matrix $C$ is a $p \times r$ matrix. 


- The **time to compute** $C$ is dominated by the **number of scalar multiplications** in line 16, which is $p \cdot q \cdot r$.


- For example, suppose that the dimensions of the matrices are $10 \times 100$, $100 \times 5$, and $5 \times 50$, respectively.

  If we multiply according to the parenthesization $((A_1  A_2) A_3 )$, we perform $10 \cdot 100 \cdot 5 = 5000$ scalar multiplications to compute the $10 \times 5$ matrix product $A_1  A_2$, plus another $10 \cdot 5  \cdot 50 =  2500$ scalar multiplications to multiply this matrix by $A_3$, for a total of $7500$ scalar multiplications. 
  
  If instead we multiply according to the parenthesization $(A_1  (A_2  A_3 ))$, we perform $100 \cdot 5 \cdot 50 = 25,000$ scalar multiplications to compute the $100\times 50$ matrix product $A_2  A_3$, plus another $10 \cdot 100 \cdot 50 = 50,000$ scalar multiplications to multiply $A_1$ by this matrix, for a total of $75,000$ scalar  ultiplications. 
  
  Thus, **computing the product** according to the **first parenthesization** is **$10$ times faster**.

<h3 align="center">Using Dynamic Programming for Matrix-Chain Multiplication</h3>

- We can state the **matrix-chain multiplication problem** as follows:

  Given a **chain** $\left \langle A_1, A_2, ..., A_n  \right \rangle $ of $n$ matrices, where for $i = 1, 2, ..., n$, matrix $A_i$ has dimension $p_{i-1} \times p_i$.
  
  **Fully parenthesize** the product $A_1  A_2  \cdots  A_n$ in a way that **minimizes** the **number of scalar multiplications**.


- Lets **count** the **number of parenthesizations**:

  **Denote** the **number of alternative parenthesizations** of a sequence of $n$ matrices by $P(n)$.
  
  When $n = 1$, we have just **one matrix** and therefore **only one way** to fully parenthesize the matrix product.
  
  When $n \geq 2$, a **fully parenthesized** matrix product **is** the **product** of **two fully parenthesized matrix subproducts**, and the split between the two subproducts may occur between the $k$-th and $(k+1)$-st matrices for any $k = 1, 2, ..., n-1$.
  
  Thus, we have:
  
  $$P(n) = 
\left\{\begin{matrix}
1 & \text{ if } n=1, \\ 
\sum_{k=1}^{n-1} P(k)P(n-k) & \text{ if } n \geq 2. 
\end{matrix}\right.$$

  The solution of this recurrence is $\Omega(2^n)$.
  
  
- The **number of solutions** is thus **exponential in** $n$, and the **brute-force method** of exhaustive search **makes for a poor strategy** when determining how to optimally parenthesize a matrix chain.


- Let's apply dynamic programming:

  In so doing, we shall follow the four-step sequence that we stated at the beginning of this lecture:
  
  1. **Characterize** the structure of an optimal solution.
  2. **Define** recursively  the value of an optimal solution.
  3. **Compute** the value of an optimal solution (typically in a bottom-up fashion).
  4. **Construct** an optimal solution from computed information.
  
  
1. **The structure of an optimal parenthesization**.

   For convenience, let us adopt the **notation** $A_{i..j}$, where $i \leq j$, for the matrix that results from evaluating the product $A_i A_{i+1} \cdots A_j$.
   
   The optimal substructure of this problem is as follows.
   
   Suppose that to optimally parenthesize $A_{i..j}$, we split the product between $A_k$ and $A_{k+1}$.
   
   Then the way we parenthesize the **prefix** subchain $A_{i..k}$ within this optimal parenthesization of $A_{i..i+1}$ must be an optimal parenthesization of $A_{i..k}k$. 
   
   **Why**? If there were a less costly way to parenthesize $A_{i..k}$, then we could substitute that parenthesization in the optimal parenthesization of $A_{i..j}$ to produce another way to parenthesize $A_{i..j}$ whose cost was lower than the optimum: a contradiction. 
   
   A similar observation holds for how we parenthesize the subchain $A_{k..j}$ in the optimal parenthesization of $A_{i..j}$: it must be an optimal parenthesization of $A_{k..j}$.
   


2. **A recursive solution**.

   Let's $m[i,j]$ be the minimum number of scalar multiplications needed to compute the matrix $A_{i..j}$.
   
   We can define $m[i,j]$ recursively as follows.
   
   if $i = j$, the problem is trivial: the chain consists of just **one matrix** $A_{i..i} = A_i$, thus $m[i,i] = 0$ for $i = 1, 2, ..., n$.
   
   To compute $m[i, j]$ when $i < j,$ we **take advantage** of the structure of an **optimal solution** from **step 1**.
   
   Let us assume that to optimally parenthesize, we split the product $A_{i..j}$ bewteen $A_k$ and $A_{k+1}$, where $i \leq k < j$. 
   
   Then, $m[i,j]$ **equals** the minimum **cost** for **computing the subproducts** $A_{i..k}$ and $A_{k..j}$, **plus** the **cost** of **multiplying these two matrices** together:
   
   $$m[i,j] = m[i,k] + m[k+1, j] + p_{i-1} p_k p_j.$$
   
   Thus, our recursive definition for the minimum cost of parenthesizing the product $A_{i..j}$ becomes:
   
   $$m[i,j] = 
\left\{\begin{matrix}
0 & \text{ if } i = j,\\ 
\min_{i \leq j < j} \{m[i,k] + m[k+1, j] + p_{i-1} p_k p_j\}& \text{ if } i < j. 
\end{matrix}\right.$$ 
 
   The $m[i,j$ values give the costs of optimal solutions to subproblems, but they do not provide all the information we need to construct an optimal solution. 
  
   To help us do so, we define $s[i,j]$ to be a value of $k$ at which we split the product $A_{i..j}$ in an optimal parenthesization. 
   
   That is, $s[i,j]$ equals a value $k$ such that $m[i,j] = m[i,k] + m[k+1, j] + p_{i-1} p_k p_j$.
   
   
3. **Computing the optimal costs**.

   Instead of computing the solution to recurrence recursively, we **compute** the **optimal cost** by using a **bottom-up approach**.
   
   As an example, we will generate matrices of the following sizes:
   
| Matrix    |      $A_1$     |      $A_2$     |     $A_3$     |     $A_4$     |      $A_5$     |      $A_6$     |
|-----------|:--------------:|:--------------:|:-------------:|:-------------:|:--------------:|:--------------:|
| Dimension | $30 \times 35$ | $35 \times 15$ | $15 \times 5$ | $5 \times 10$ | $10 \times 20$ | $20 \times 25$ |

In [8]:
import numpy as np

def matrixChainOrder(p):
    n = len(p)-1
    m = np.zeros((n+1,n+1))
    s = np.zeros((n+1,n+1))
    for l in range(2, n+1):
        for i in range(1, n - l + 2):
            j = i + l - 1
            m[i,j]= np.infty
            for k in range(i, j):
                q = m[i,k] + m[k+1,j] + p[i-1] * p[k] * p[j]
                if q < m[i,j]:
                    m[i,j] = q
                    s[i,j] = k
    return m, s

In [9]:
A1 = np.random.rand(30, 35)
A2 = np.random.rand(35, 15)
A3 = np.random.rand(15,  5)
A4 = np.random.rand( 5, 10)
A5 = np.random.rand(10, 20)
A6 = np.random.rand(20, 25)

B = [A1, A2, A3, A4, A5, A6]

p = np.empty(len(B)+1)
p[0] = int(B[0].shape[0])
for i in range(len(B)):
    p[i+1] = int(B[i].shape[1])
    
m, s = matrixChainOrder(p)
print(m)
print(s)

[[    0.     0.     0.     0.     0.     0.     0.]
 [    0.     0. 15750.  7875.  9375. 11875. 15125.]
 [    0.     0.     0.  2625.  4375.  7125. 10500.]
 [    0.     0.     0.     0.   750.  2500.  5375.]
 [    0.     0.     0.     0.     0.  1000.  3500.]
 [    0.     0.     0.     0.     0.     0.  5000.]
 [    0.     0.     0.     0.     0.     0.     0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 3. 3. 3.]
 [0. 0. 0. 2. 3. 3. 3.]
 [0. 0. 0. 0. 3. 3. 3.]
 [0. 0. 0. 0. 0. 4. 5.]
 [0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0.]]


<center><img src="images/L6_Tables.png" width="900" alt="Example" /></center>

4. **Step 4: Constructing an optimal solution**.

   Although `matrixChainOrder` procedure determines the optimal number of scalar multiplications needed to compute a matrix-chain product, it does not directly show how to multiply the matrices.
   
   The initial call `printOptimalParenthesis(s, 1, n)` procedure prints an optimal parenthesization of $\left \langle A_1, A_2, ..., A_n  \right \rangle $:

In [10]:
s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 3., 3., 3.],
       [0., 0., 0., 2., 3., 3., 3.],
       [0., 0., 0., 0., 3., 3., 3.],
       [0., 0., 0., 0., 0., 4., 5.],
       [0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
import numpy as np

def printOptimalParenthesis(s, i, j):
    if i == j:
        print(f"A{i}", end=' ')
    else: 
        print("(", end=' ')
        printOptimalParenthesis(s, i, int(s[i,j]))
        printOptimalParenthesis(s, int(s[i,j]+1), j)
        print(")", end=' ')

printOptimalParenthesis(s, 1, 6)

( ( A1 ( A2 A3 ) ) ( ( A4 A5 ) A6 ) ) 

<h1 align="center">End of Lecture</h1>