Course: **Algorithms and Their Analysis**
<br>

Title: **Lecture 3 - Matrix Multiplication**
<br>
Speaker: **Dr. Shota Tsiskaridze**


Bibliography:
<br> 
[1] Cormen, Thomas H. and Leiserson, Charles Eric and Rivest, Ronald Linn and Stein, Clifford Seth, *Introduction to Algorithms, 3rd Edition*, MIT Press, 2009 


<h1 align="center">Matrix Multiplication</h1>

- If $A = (a_{ij})$ and $B = (b_{ij})$ are square $n \times n$ matrices, then in the product $C = A \cdot B$ we define the entry $c_{ij}$, for $i, j = 1, 2, \cdots, n$ by:

  $$c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}.$$
  
  
<img src="images/L3_Matrix_Multiplication.png" width="800" alt="Example"  align="center"/>


<h3 align="center">A Square Matrix Multiplicaton</h3>

- Let's write the code that calculates $C$ directly.


- $\texttt{squareMatrixMultiply(A, B)}$:

In [1]:
import numpy as np

In [2]:
def squareMatrixMultiply(A, B):
    l = A.shape[0]
    m = A.shape[1]
    n = B.shape[1]
    C = np.empty((l, n))
    for i in range(l):
        for j in range(n):
            C[[i],[j]] = 0
            for k in range(m):
                C[[i],[j]] = C[[i],[j]] + A[[i],[k]] *  B[[k],[j]] 
    return C            

In [3]:
l = 10
m = 5
n = 6

A = np.random.random(size=(l, m))
B = np.random.random(size=(m, n))

C = squareMatrixMultiply(A,B)
print(C)

[[1.30536617 1.37436726 0.63359249 1.63995262 1.14679841 0.79734518]
 [1.83908714 0.99807115 0.88654619 1.83688413 1.17454512 1.07896399]
 [1.45295066 0.97567939 0.64912126 1.52339553 0.94051801 0.73005506]
 [1.89562212 1.23861608 0.97481515 2.03347646 1.40126533 1.25359771]
 [1.6855145  1.13716599 0.84016285 1.69900975 1.08610528 1.18754499]
 [1.77678019 1.18816424 0.89238952 1.80780758 1.12047863 1.1614089 ]
 [1.54486376 1.30747314 0.76723733 1.85510932 1.27262391 0.82871169]
 [1.27145929 0.90313446 0.58866707 1.36692471 0.90967374 0.74613316]
 [1.7597874  0.99836772 0.95208401 1.79639246 1.18990893 1.21182407]
 [1.3602556  1.14532438 0.46087023 1.29883249 0.77201665 0.88139486]]


- We must compute $n^2$ matrix entries, and each is the sum of $n$ values, thus the $\texttt{squareMatrixMultiply}$ procedure takes $\Theta(n^3)$ time.

<h3 align="center">A Simple Divide-and-Conquer Algorithm</h3>

- Suppose that we partition each of $A$, $B$, and $C$ into four $\frac{n}{2} \cdot \frac{n}{2}$ matricies:

  $$A = 
\begin{pmatrix}
A_{11} & A_{12}\\ 
A_{21} & A_{22}
\end{pmatrix},
B = 
\begin{pmatrix}
B_{11} & B_{12}\\ 
B_{21} & B_{22}
\end{pmatrix},
C = 
\begin{pmatrix}
C_{11} & C_{12}\\ 
C_{21} & C_{22}
\end{pmatrix},
$$

  so that we rewrite the equation $C = A \cdot B$ as:
  
  $$
\begin{pmatrix}
C_{11} & C_{12}\\ 
C_{21} & C_{22}
\end{pmatrix} = 
\begin{pmatrix}
A_{11} & A_{12}\\ 
A_{21} & A_{22}
\end{pmatrix} \cdot 
\begin{pmatrix}
B_{11} & B_{12}\\ 
B_{21} & B_{22}
\end{pmatrix}
.$$

- This corresponds to the four equations:

  $$C_{11} = A_{11} \cdot B_{11} + A_{12} \cdot B_{21},$$
  $$C_{12} = A_{11} \cdot B_{12} + A_{12} \cdot B_{22},$$
  $$C_{21} = A_{21} \cdot B_{11} + A_{22} \cdot B_{21},$$
  $$C_{22} = A_{21} \cdot B_{12} + A_{22} \cdot B_{22},$$
  
  or in matrix form:
  
  $$\begin{pmatrix}
C_{11} & C_{12}\\ 
C_{21} & C_{22}
\end{pmatrix} = 
\begin{pmatrix}
A_{11} \cdot B_{11} + A_{12} \cdot B_{21} & A_{11} \cdot B_{12} + A_{12} \cdot B_{22}\\ 
A_{21} \cdot B_{11} + A_{22} \cdot B_{21} & A_{21} \cdot B_{12} + A_{22} \cdot B_{22}
\end{pmatrix}$$
  
  
  
- $\texttt{squareMatrixMultiplicationRecursive(A, B)}$:

In [4]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [5]:
def divide(A): 
    """ 
    Divide a given matrix A into four matricies. 
    Input: n x n matrix 
    Output: tuple containing four n/2 x n/2 matrices corresponding to A11, A12, A21, A22
    """
    m, n = A.shape 
    row, col = m//2, n//2
    A11 = A[:row, :col]
    A12 = A[:row, col:]
    A21 = A[row:, :col]
    A22 = A[row:, col:] 
    return A11, A12, A21, A22

In [6]:
def squareMatrixMultiplicationRecursive(A, B): 
    """ 
    Computes matrix product by D&C approach, recursively. 
    Input: n x n matrix A and n x n marix Y 
    Output: n x n matrix, product of A and B 
    """
    # Base case when size of matrices is 1x1 
    if len(A) == 1: 
        return A * B 
  
    # Splitting the matrices into quadrants recursively.
    A11, A12, A21, A22 = divide(A) 
    B11, B12, B21, B22 = divide(B) 
      
    # Computing the values of the 4 quadrants of the final matrix c 
    C11 = squareMatrixMultiplicationRecursive(A11, B11) + squareMatrixMultiplicationRecursive (A12, B21)
    C12 = squareMatrixMultiplicationRecursive(A11, B12) + squareMatrixMultiplicationRecursive (A12, B22)
    C21 = squareMatrixMultiplicationRecursive(A21, B11) + squareMatrixMultiplicationRecursive (A22, B21)
    C22 = squareMatrixMultiplicationRecursive(A21, B22) + squareMatrixMultiplicationRecursive (A22, B22)
  
    # Combining the 4 quadrants into a single matrix by stacking horizontally and vertically. 
    C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))  
  
    return C

In [7]:
C = squareMatrixMultiplicationRecursive(A,B)
print(C)

[[ 90 100 110 120]
 [202 276 254 328]
 [314 356 550 592]
 [426 596 758 928]]


- In $\texttt{squareMatrixMultiplicationRecursive}$ procedure we do $8$ **multiplications** for matrices of size $n/2 \times n/2$ and $4$ **additions**. 


- **Addition of two matrices** takes $\Theta(n^2)$ time, so the running time of this procedure can be written as follows:

  $$T(n) = 8T(n/2) + \Theta(n^2).$$
  
  
- From **Master's Theorem** we can obtain that **running time** of this procedure is $\Theta(n^3)$, which is unfortunately same as the above naive algorithm.

<h3 align="center">Strassen’s Method</h3>

- In the above **D&C** algorithm, the main component for high running time is **8 recursive calls**.


- The idea of **Strassen’s Method** is to **reduce** the **number** of recursive calls **to $7$**. 


- **Strassen’s Method** is similar to above simple **D&C** algorithmin the sense that this method also divide matrices to sub-matrices of size $n/2 \times n/2$ as shown in the above diagram, but in **Strassen’s Method**, the four sub-matrices of result are calculated using following formula:

  $$S_1  = B_{12} - B_{22},$$
  $$S_2  = A_{11} + A_{12},$$
  $$S_3  = A_{21} - A_{22},$$
  $$S_4  = B_{21} - B_{11},$$
  $$S_5  = A_{11} + A_{22},$$
  $$S_6  = B_{11} + B_{22},$$
  $$S_7  = A_{12} - A_{22},$$
  $$S_8  = B_{21} + B_{22},$$
  $$S_9  = A_{11} - A_{21},$$
  $$S_{10} = B_{11} + B_{12},$$
 
  and
  
  $$P_1 = A_{11} \cdot S_1,$$
  $$P_2 = S_2 \cdot B_{22},$$
  $$P_3 = S_3 \cdot B_{11},$$
  $$P_4 = A_{22} \cdot S_4,$$
  $$P_5 = S_5 \cdot S_6,$$
  $$P_6 = S_7 \cdot S_8,$$
  $$P_7 = S_9 \cdot S_{10}.$$
  
  
  
  
  
- The $C = A \cdot B$ can be calculated using this seven values:

  $$\begin{pmatrix}
C_{11} & C_{12}\\ 
C_{21} & C_{22}
\end{pmatrix} = 
\begin{pmatrix}
P_5 + P_4 - P_2 + P_6 & P_1 + P_2\\ 
P_3 + P_4  & P_5 + P_1 - P_3 + P_7
\end{pmatrix}$$


- Lets write the code for **Strassen's Method**.


- $\texttt{squareMatrixMultiplicationStrassen(A, B)}$:

In [8]:
def squareMatrixMultiplicationStrassen(A, B): 
    """ 
    Computes matrix product by D&C approach, recursively. 
    Input: n x n matrix A and n x n marix Y 
    Output: n x n matrix, product of A and B 
    """
    # Base case when size of matrices is 1x1 
    if len(A) == 1: 
        return A * B 
  
    # Splitting the matrices into quadrants recursively.
    A11, A12, A21, A22 = divide(A) 
    B11, B12, B21, B22 = divide(B) 

    # Computing the 7 products, recursively (p1, p2...p7) 
    p1 = squareMatrixMultiplicationStrassen(A11, B12 - B22)
    p2 = squareMatrixMultiplicationStrassen(A11 + A12, B22)
    p3 = squareMatrixMultiplicationStrassen(A21 + A22, B11)
    p4 = squareMatrixMultiplicationStrassen(A22, B21 - B11)
    p5 = squareMatrixMultiplicationStrassen(A11 + A22, B11 + B22)
    p6 = squareMatrixMultiplicationStrassen(A12 - A22, B21 + B22)
    p7 = squareMatrixMultiplicationStrassen(A11 - A21, B11 + B12)
    

    # Computing the values of the 4 quadrants of the final matrix c 
    C11 = p5 + p4 - p2 + p6   
    C12 = p1 + p2            
    C21 = p3 + p4             
    C22 = p1 + p5 - p3 - p7   
  
    # Combining the 4 quadrants into a single matrix by stacking horizontally and vertically. 
    C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))  
  
    return C

In [9]:
C = squareMatrixMultiplicationStrassen(A,B)
print(C)

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]


- In $\texttt{squareMatrixMultiplicationStrassen}$ procedure we do $7$ **multiplications** for matrices of size $n/2 \times n/2$, so the running time of this procude can be written as follows:

  $$T(n) = 7T(n/2) + \Theta(n^2).$$


- - From **Master's Theorem** we can obtain that **running time** of this procedure is $\Theta(n^{\lg 7 })$, which is approximately $\Theta(n^{2.807})$.

<h1 align="center">End of Appendix B</h1>